# Generated by Django 3.0.7 on 2020-07-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(default='null', max_length=300)),
                ('BrandLogo', models.ImageField(upload_to='')),
            ],
        ),
    ]
