# Generated by Django 3.0.7 on 2020-07-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebrands',
            name='BrandLogo',
            field=models.ImageField(upload_to='brand_logo'),
        ),
    ]
