# Generated by Django 3.0.7 on 2020-07-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200716_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=300)),
                ('model_number', models.IntegerField(max_length=300)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.PhoneBrands')),
            ],
        ),
    ]
