# Generated by Django 3.0.7 on 2020-07-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_phonemodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodels',
            name='model_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='phonemodels',
            name='model_number',
            field=models.CharField(max_length=300),
        ),
    ]
