# Generated by Django 3.0.7 on 2020-07-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200719_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonemodels',
            old_name='brand',
            new_name='brand_name',
        ),
    ]
