# Generated by Django 3.0.7 on 2020-07-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200720_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodels',
            name='model_img',
            field=models.ImageField(default='null', upload_to='model_img'),
            preserve_default=False,
        ),
    ]
