# Generated by Django 3.0.7 on 2020-08-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_phonemodels_model_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonemodels',
            old_name='model_number',
            new_name='model_variant',
        ),
    ]
